# Generated by Django 3.0.8 on 2020-10-16 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('helmet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('helmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helmet.Helmet')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
